sonar.projectKey=Javier-Fajardo-Balarezo_medpapaya-online
sonar.organization=javier-fajardo-balarezo

sonar.projectName=MedPapaya
sonar.sourceEncoding=UTF-8

sonar.sources=backend,frontend,Dockerfile
sonar.tests=tests

sonar.python.coverage.reportPaths=coverage.xml

sonar.exclusions=backend/model/**,backend/dataset/**,**/*.keras,**/__pycache__/**,.venv/**

sonar.coverage.exclusions=frontend/**,Dockerfile
